inspect zip file

diff --git a/.github/actions/module-deploy/action.yml b/.github/actions/module-deploy/action.yml
--- a/.github/actions/module-deploy/action.yml
+++ b/.github/actions/module-deploy/action.yml
@@ -65,6 +65,15 @@ runs:
       shell: bash
       run: node ./deploy.js --deployFile ./downloaded-artifacts/${{ inputs.zipFileName }}
 
+    - name: Inspect downloaded zip file
+      working-directory: module/${{ inputs.moduleName }}/func/deploy/code
+      shell: bash
+      run: |
+        echo "Inspecting zip: downloaded-artifacts/${{ inputs.zipFileName }}"
+        unzip -l downloaded-artifacts/${{ inputs.zipFileName }}
+        echo "Simulating failure"
+          exit 1
+
     - name: Check if verify step exists
       working-directory: module/${{ inputs.moduleName }}/func/deploy
       id: check_verify
