test ui upload

diff --git a/.github/workflows/MainWorkflow.yml b/.github/workflows/MainWorkflow.yml
--- a/.github/workflows/MainWorkflow.yml
+++ b/.github/workflows/MainWorkflow.yml
@@ -245,6 +245,11 @@ jobs:
       - name: Echo job name
         run: echo "Job name is ${{ github.job }}"
 
+      - name: Simulate failure
+        run: |
+          echo "Simulating failure"
+          exit 1
+
       - name: Checkout code
         uses: actions/checkout@v4
 
@@ -343,6 +348,9 @@ jobs:
     steps:
       - name: Echo job name
         run: echo "Job name is ${{ github.job }}"
+
+      - name: Checkout code
+        uses: actions/checkout@v4
 
       - name: Setup pnpm environment
         uses: ./.github/actions/setup-pnpm
