test root status

diff --git a/.github/workflows/MainWorkflow.yml b/.github/workflows/MainWorkflow.yml
--- a/.github/workflows/MainWorkflow.yml
+++ b/.github/workflows/MainWorkflow.yml
@@ -13,17 +13,179 @@ on:
 
 jobs:
   # root pipelines
-  root:
-    uses: ./.github/workflows/rootPipeline.yml
+  buildRoot:
+    name: Build Root
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      security-events: write
+      actions: read
+    outputs:
+      result: ${{ steps.result.outputs.result }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # - name: Setup pnpm environment
+      #   uses: ./.github/actions/setup-azure
+
+      - name: Set output
+        id: result
+        run: echo "result=true" >> $GITHUB_OUTPUT
+
+  deployRootDev:
+    name: Deploy Root Dev
+    needs: buildRoot
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      security-events: write
+      actions: read
+    outputs:
+      result: ${{ steps.result.outputs.result }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # - name: Setup pnpm environment
+      #   uses: ./.github/actions/setup-azure
+
+      - name: Set output
+        id: result
+        run: echo "result=true" >> $GITHUB_OUTPUT
+
+  testRootDev:
+    name: Test Root Dev
+    needs: deployRootDev
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      security-events: write
+      actions: read
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # - name: Setup pnpm environment
+      #   uses: ./.github/actions/setup-azure
+
+  deployRootTest:
+    name: Deploy Root Test
+    needs: testRootDev
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      security-events: write
+      actions: read
+    outputs:
+      result: ${{ steps.result.outputs.result }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # - name: Setup pnpm environment
+      #   uses: ./.github/actions/setup-azure
+
+      - name: Fail intentionally
+        run: |
+          echo "Simulating failure"
+          exit 1
+
+      - name: Set output
+        id: result
+        run: echo "result=true" >> $GITHUB_OUTPUT
+
+  testRootTest:
+    name: Test Root Test
+    needs: deployRootTest
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      security-events: write
+      actions: read
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # - name: Setup pnpm environment
+      #   uses: ./.github/actions/setup-azure
+
+  deployRootProd:
+    name: Deploy Root Prod
+    needs: testRootTest
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      security-events: write
+      actions: read
+    outputs:
+      result: ${{ steps.result.outputs.result }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # - name: Setup pnpm environment
+      #   uses: ./.github/actions/setup-azure
+
+      - name: Set output
+        id: result
+        run: echo "result=true" >> $GITHUB_OUTPUT
+
+  testRootProd:
+    name: Test Root Prod
+    needs: deployRootProd
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      security-events: write
+      actions: read
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # - name: Setup pnpm environment
+      #   uses: ./.github/actions/setup-azure
+  export:
+    runs-on: ubuntu-latest
+    needs:
+      - buildRoot
+      - deployRootDev
+      - deployRootTest
+      - deployRootProd
+    if: always()
+    outputs:
+      build: ${{ needs.buildRoot.outputs.result || 'false' }}
+      deployDev: ${{ needs.deployRootDev.outputs.result || 'false' }}
+      deployTest: ${{ needs.deployRootTest.outputs.result || 'false' }}
+      deployProd: ${{ needs.deployRootProd.outputs.result || 'false' }}
+    steps:
+      - run: |
+          echo "Export results"
+        # echo "build=${{ needs.buildRoot.outputs.result || 'false' }}" >> $GITHUB_ENV
+        # echo "deployDev=${{ needs.deployRootDev.outputs.result || 'false' }}" >> $GITHUB_ENV
+        # echo "deployTest=${{ needs.deployRootTest.outputs.result || 'false' }}" >> $GITHUB_ENV
+        # echo "deployProd=${{ needs.deployRootProd.outputs.result || 'false' }}" >> $GITHUB_ENV
 
   # modules pipelines
   profile:
-    needs: root
+    needs: export
+    if: always()
     uses: ./.github/workflows/profilePipeline.yml
+    with:
+      build: ${{ needs.export.outputs.build }}
+      deployDev: ${{ needs.export.outputs.deployDev }}
+      deployTest: ${{ needs.export.outputs.deployTest }}
+      deployProd: ${{ needs.export.outputs.deployProd }}
 
-  # quest3Tier:
-  #   needs: root
-  #   uses: ./.github/workflows/quest3TierPipeline.yml
+  quest3Tier:
+    needs: export
+    if: always()
+    uses: ./.github/workflows/quest3TierPipeline.yml
+    with:
+      build: ${{ needs.export.outputs.build }}
+      deployDev: ${{ needs.export.outputs.deployDev }}
+      deployTest: ${{ needs.export.outputs.deployTest }}
+      deployProd: ${{ needs.export.outputs.deployProd }}
 
   # quest5Tier:
   #   needs: root
